set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_C_COMPILER arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(SHIZUKU_PLATFORM_NAME pico_sdk CACHE STRING shizuku_platform_name FORCE)
set(SHIZUKU_SYSTEM_PROCESSOR RP2040 CACHE STRING shizuku_processor_name FORCE)
add_compile_options(-mcpu=cortex-m0plus)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 20)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)