set(CMAKE_SYSTEM_NAME UEFI)
set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
set(CMAKE_SYSTEM_INCLUDE_PATH /include )
set(CMAKE_SYSTEM_LIBRARY_PATH /lib )
set(CMAKE_SYSTEM_PROGRAM_PATH /bin )
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -mno-red-zone -fno-stack-protector -fshort-wchar -O3 -nostdlib -fno-exceptions -fno-rtti -target x86_64-windows-msvc -Wno-microsoft-static-assert -ffreestanding")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -mno-red-zone -fno-stack-protector -fshort-wchar -O3 -nostdlib -fno-exceptions --static -fno-rtti -target x86_64-windows-msvc -Wno-microsoft-static-assert -ffreestanding")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-subsystem:efi_application -fuse-ld=lld")
